<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-01-24T22:56:17 IST" name="Suite" finished-at="2023-01-24T22:56:50 IST" duration-ms="32757">
    <groups>
    </groups>
    <test started-at="2023-01-24T22:56:17 IST" name="Test" finished-at="2023-01-24T22:56:50 IST" duration-ms="32757">
      <class name="functional_TestCase.NegativeTestFormData">
        <test-method is-config="true" signature="openBrowser(java.lang.String)[pri:0, instance:functional_TestCase.NegativeTestFormData@2d7275fc]" started-at="2023-01-24T22:56:17 IST" name="openBrowser" finished-at="2023-01-24T22:56:34 IST" duration-ms="16693" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method is-config="true" signature="startReport()[pri:0, instance:functional_TestCase.NegativeTestFormData@2d7275fc]" started-at="2023-01-24T22:56:34 IST" name="startReport" finished-at="2023-01-24T22:56:34 IST" duration-ms="399" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method signature="negativeTest()[pri:0, instance:functional_TestCase.NegativeTestFormData@2d7275fc]" started-at="2023-01-24T22:56:35 IST" name="negativeTest" finished-at="2023-01-24T22:56:49 IST" duration-ms="14651" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to get Error Message expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to get Error Message expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at functional_TestCase.NegativeTestFormData.negativeTest(NegativeTestFormData.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeTest -->
        <test-method is-config="true" signature="close()[pri:0, instance:functional_TestCase.NegativeTestFormData@2d7275fc]" started-at="2023-01-24T22:56:49 IST" name="close" finished-at="2023-01-24T22:56:50 IST" duration-ms="495" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="endReport()[pri:0, instance:functional_TestCase.NegativeTestFormData@2d7275fc]" started-at="2023-01-24T22:56:50 IST" name="endReport" finished-at="2023-01-24T22:56:50 IST" duration-ms="463" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- functional_TestCase.NegativeTestFormData -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
